language: cpp

compiler:
  - gcc
  - clang

os:
  - linux


sudo: false


env:
  - DGTALTYPE="-DBUILD_EXAMPLES=OFF -DDGTAL_BUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DWITH_ITK=false" 

addons:
  apt:
   sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
   packages:
    - libhdf5-serial-dev
    - doxygen
    - doxygen-latex
    - libgmp-dev
    - libgdcm2-dev 
    - g++-4.8
    - gcc-4.8
    - libqglviewer-dev
    - libboost-dev
before_install:
  - env
  - export SRC_DIR="`pwd`"
  - if [ $CXX == "g++" ]; then export CXX="g++-4.8"  CC="gcc-4.8" CCOMPILER="gcc-4.8" CXXCOMPILER="g++-4.8"; fi

before_script:
  - 'echo "using gcc : : ccache $CXX : <cflags>-std=c11 <cxxflags>-std=c++11 ;" > ~/user-config.jam'
  - 'echo "using clang : : ccache $CXX : <cflags>-std=c11 <cxxflags>-std=c++11 ;" >> ~/user-config.jam'
  - cd $SRC_DIR
  - git clone git://github.com/DGtal-team/DGtal.git
  - cd DGtal
  - cmake . $DGTALTYPE  -DCMAKE_CXX_COMPILER=$CXXCOMPILER -DCMAKE_C_COMPILER=$CCOMPILER 
  - make 
  - cd ..

script: 
  - cmake . -DCMAKE_BUILD_TYPE=Debug -DDGtal_DIR=$PWD/DGtal -DCMAKE_CXX_COMPILER=$CXXCOMPILER -DCMAKE_C_COMPILER=$CCOMPILER 
  - make

